const basics = {
  colors: {
    black: '#000000',
    blackRed: '#420f0f',
    white: '#ffffff',
    creamWhite: '#FFFEFC',
    bloodRed: '#800020',
    fadedRed: '#AA6969',
    solidBlue: '#2844A0',
    neonBlue: '#002FAD',
    fadedBlue: '#9EADD5',
    chalkBlue: '#727884',
    soapBlue: '#425bc2',
    washBlue: '#EDFCFF',
    solidGreen: '#247013',
    washGreen: '#dcffd4',
    deepGreen: '#194f0d',
    yellow: '#FFF11B',
    washOrange: '#fff8eb',
    citrus: '#E0861F',
    chalkRed: '#C1B6B6',
    chalk: '#bababa',
    deepRed: '#650019',
    deepBlue: '#010D4E',
    rose: '#AA405B',
    pink: '#DBA3B1',
    paper: '#FAFAC8',
    wood: '#855E42',
    nightShift: '#D1D1C0',
    chocolate: '#9e4e15',
  },
  transition: 'all 0.25s cubic-bezier(0.3, 0.3, 0.3, 0.3)',
  fonts: {
    Monoton: 'Monoton, Roboto Mono, Lucida Console, Monaco, monospace',
    NotoSans: 'Noto Sans, Roboto, San Francisco, Helvetica Neue, Segoe UI, Arial, sans-serif',
    LilitaOne: 'Lilita One, Noto Sans, Roboto, San Francisco, Helvetica Neue, Segoe UI, Arial ',
    MadeSoulmazeBrush: 'Made Soulmaze Brush, Be Vietnam',
    BeVietnam: 'Be Vietnam, Lilita One, Noto Sans, Roboto, San Francisco, Helvetica Neue, Segoe UI, Arial',
  },
  fontSize: {
    large: '50px',
    xlarge: '85px',
    xxlarge: '100px',
    small: '15px',
    xsmall: '12px',
    xxsmall: '10px',
    medium: '20px',
  },
};

export default basics;
